# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Avoid prompt from tzdata
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1

WORKDIR /app

# Copy only necessary files
COPY setup.py pyproject.toml mcp.json main.py smithery.yaml README.md LICENSE .

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libffi-dev \
    && pip install --no-cache-dir . \
    && apt-get purge -y --auto-remove gcc libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Expose nothing (stdio-based MCP)

ENTRYPOINT ["python3", "main.py"]
